### PR TITLE
Adding in the base tests we need for HEVM

### PR DESCRIPTION
**Pull request by andy8052**
This should be all the tests we need for a base coverage of the MKR authority change in HEVM. If we can think of more tests needed we can add them going forward.

### CODE REVIEW

**Review by kmbarry1 — APPROVED** [review]
The test itself LGTM; any particular reason you went with the copying-pasting-code rather than adding-`dss`-as-a-submodule approach? I feel the latter is a cleaner/more maintainable pattern.

**Comment by andy8052** [comment]
The main reason was because I had to (at least to get this base level) manipulate the code a bit in flap and flop. I think if I were to just use the submodule I would need to deploy a lot more of DSS which we don't actually care about testing for this repo. I could be wrong here though

**Comment by kmbarry1** [comment]
Hmmmm, I'm even less comfortable using copy-pasted code if it's _also_ modified :).

Let's see, looks like you'd need at a minimum the `Vat`. Any other contracts?

Regarding getting rid of the auction delay to call `deal` immediately--couldn't we just call `hevm.warp()`?

**Comment by gbalabasquer** [comment]
What we could do to keep this repo clean is transferring this whole test to a new one like `mkr-authority-mainnet-test`.
There we can import this one but also `dss-deploy` and do a full deployment. In `dss-deploy` tests we have the steps to force `flap` and `flop` auctions.
As soon as we have a mainnet release, the deployed system can be changed to that one and remove the `dss-deploy` dependency.

**Comment by andy8052** [comment]
Oh yeah that is a good idea. I will look into that today

**Pull request merged**
